//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEng_ViewModel.WCFContact_Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.UserDictionaryEntryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.AddedSharedUserGroupDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.IntegratedVacabularyEntryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.UserGroupDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.UserSettingsDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.VacabularyDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnEng_ViewModel.WCFContact_Server.UserDTO))]
    public partial class DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDictionaryEntryDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDictionaryEntryDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DictionaryGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.StatusOfLearning StatusOfLearningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserGroupsGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UsersGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO WordOfDictionaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DictionaryGUID {
            get {
                return this.DictionaryGUIDField;
            }
            set {
                if ((this.DictionaryGUIDField.Equals(value) != true)) {
                    this.DictionaryGUIDField = value;
                    this.RaisePropertyChanged("DictionaryGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.StatusOfLearning StatusOfLearning {
            get {
                return this.StatusOfLearningField;
            }
            set {
                if ((this.StatusOfLearningField.Equals(value) != true)) {
                    this.StatusOfLearningField = value;
                    this.RaisePropertyChanged("StatusOfLearning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserGroupsGUID {
            get {
                return this.UserGroupsGUIDField;
            }
            set {
                if ((this.UserGroupsGUIDField.Equals(value) != true)) {
                    this.UserGroupsGUIDField = value;
                    this.RaisePropertyChanged("UserGroupsGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UsersGUID {
            get {
                return this.UsersGUIDField;
            }
            set {
                if ((this.UsersGUIDField.Equals(value) != true)) {
                    this.UsersGUIDField = value;
                    this.RaisePropertyChanged("UsersGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO WordOfDictionary {
            get {
                return this.WordOfDictionaryField;
            }
            set {
                if ((object.ReferenceEquals(this.WordOfDictionaryField, value) != true)) {
                    this.WordOfDictionaryField = value;
                    this.RaisePropertyChanged("WordOfDictionary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictionaryEntryDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class DictionaryEntryDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreatedByUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfAddingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfLastChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfTranslationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UsersGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> VacabulariesGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((this.CreatedByUserField.Equals(value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfAdding {
            get {
                return this.DateOfAddingField;
            }
            set {
                if ((this.DateOfAddingField.Equals(value) != true)) {
                    this.DateOfAddingField = value;
                    this.RaisePropertyChanged("DateOfAdding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfLastChange {
            get {
                return this.DateOfLastChangeField;
            }
            set {
                if ((this.DateOfLastChangeField.Equals(value) != true)) {
                    this.DateOfLastChangeField = value;
                    this.RaisePropertyChanged("DateOfLastChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfTranslation {
            get {
                return this.LanguageOfTranslationField;
            }
            set {
                if ((this.LanguageOfTranslationField.Equals(value) != true)) {
                    this.LanguageOfTranslationField = value;
                    this.RaisePropertyChanged("LanguageOfTranslation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfWord {
            get {
                return this.LanguageOfWordField;
            }
            set {
                if ((this.LanguageOfWordField.Equals(value) != true)) {
                    this.LanguageOfWordField = value;
                    this.RaisePropertyChanged("LanguageOfWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transcription {
            get {
                return this.TranscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.TranscriptionField, value) != true)) {
                    this.TranscriptionField = value;
                    this.RaisePropertyChanged("Transcription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Translation {
            get {
                return this.TranslationField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationField, value) != true)) {
                    this.TranslationField = value;
                    this.RaisePropertyChanged("Translation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UsersGUID {
            get {
                return this.UsersGUIDField;
            }
            set {
                if ((this.UsersGUIDField.Equals(value) != true)) {
                    this.UsersGUIDField = value;
                    this.RaisePropertyChanged("UsersGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> VacabulariesGUID {
            get {
                return this.VacabulariesGUIDField;
            }
            set {
                if ((this.VacabulariesGUIDField.Equals(value) != true)) {
                    this.VacabulariesGUIDField = value;
                    this.RaisePropertyChanged("VacabulariesGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddedSharedUserGroupDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class AddedSharedUserGroupDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserGroupsGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UsersGUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGroupsGUID {
            get {
                return this.UserGroupsGUIDField;
            }
            set {
                if ((this.UserGroupsGUIDField.Equals(value) != true)) {
                    this.UserGroupsGUIDField = value;
                    this.RaisePropertyChanged("UserGroupsGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UsersGUID {
            get {
                return this.UsersGUIDField;
            }
            set {
                if ((this.UsersGUIDField.Equals(value) != true)) {
                    this.UsersGUIDField = value;
                    this.RaisePropertyChanged("UsersGUID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegratedVacabularyEntryDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class IntegratedVacabularyEntryDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfTranslationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid VacabularyGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfTranslation {
            get {
                return this.LanguageOfTranslationField;
            }
            set {
                if ((this.LanguageOfTranslationField.Equals(value) != true)) {
                    this.LanguageOfTranslationField = value;
                    this.RaisePropertyChanged("LanguageOfTranslation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages LanguageOfWord {
            get {
                return this.LanguageOfWordField;
            }
            set {
                if ((this.LanguageOfWordField.Equals(value) != true)) {
                    this.LanguageOfWordField = value;
                    this.RaisePropertyChanged("LanguageOfWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Translation {
            get {
                return this.TranslationField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationField, value) != true)) {
                    this.TranslationField = value;
                    this.RaisePropertyChanged("Translation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid VacabularyGUID {
            get {
                return this.VacabularyGUIDField;
            }
            set {
                if ((this.VacabularyGUIDField.Equals(value) != true)) {
                    this.VacabularyGUIDField = value;
                    this.RaisePropertyChanged("VacabularyGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserGroupDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SharedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UsersGUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Shared {
            get {
                return this.SharedField;
            }
            set {
                if ((this.SharedField.Equals(value) != true)) {
                    this.SharedField = value;
                    this.RaisePropertyChanged("Shared");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UsersGUID {
            get {
                return this.UsersGUIDField;
            }
            set {
                if ((this.UsersGUIDField.Equals(value) != true)) {
                    this.UsersGUIDField = value;
                    this.RaisePropertyChanged("UsersGUID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSettingsDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserSettingsDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages DefaultLanguageForLearningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LearnEng_ViewModel.WCFContact_Server.Languages NativeLanguageOfUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WithoutSoundField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages DefaultLanguageForLearning {
            get {
                return this.DefaultLanguageForLearningField;
            }
            set {
                if ((this.DefaultLanguageForLearningField.Equals(value) != true)) {
                    this.DefaultLanguageForLearningField = value;
                    this.RaisePropertyChanged("DefaultLanguageForLearning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LearnEng_ViewModel.WCFContact_Server.Languages NativeLanguageOfUser {
            get {
                return this.NativeLanguageOfUserField;
            }
            set {
                if ((this.NativeLanguageOfUserField.Equals(value) != true)) {
                    this.NativeLanguageOfUserField = value;
                    this.RaisePropertyChanged("NativeLanguageOfUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WithoutSound {
            get {
                return this.WithoutSoundField;
            }
            set {
                if ((this.WithoutSoundField.Equals(value) != true)) {
                    this.WithoutSoundField = value;
                    this.RaisePropertyChanged("WithoutSound");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacabularyDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class VacabularyDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : LearnEng_ViewModel.WCFContact_Server.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserSettingsGUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserSettingsGUID {
            get {
                return this.UserSettingsGUIDField;
            }
            set {
                if ((this.UserSettingsGUIDField.Equals(value) != true)) {
                    this.UserSettingsGUIDField = value;
                    this.RaisePropertyChanged("UserSettingsGUID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusOfLearning", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model")]
    public enum StatusOfLearning : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Learned = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnRepeat = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotLearnedYet = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Languages", Namespace="http://schemas.datacontract.org/2004/07/LearnEng_Server.Model")]
    public enum Languages : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rus = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eng = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFContact_Server.IWCFContact_Server")]
    public interface IWCFContact_Server {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/AllUserGroupsOfUser", ReplyAction="http://tempuri.org/IWCFContact_Server/AllUserGroupsOfUserResponse")]
        LearnEng_ViewModel.WCFContact_Server.UserGroupDTO[] AllUserGroupsOfUser(LearnEng_ViewModel.WCFContact_Server.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/AllUserGroupsOfUser", ReplyAction="http://tempuri.org/IWCFContact_Server/AllUserGroupsOfUserResponse")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserGroupDTO[]> AllUserGroupsOfUserAsync(LearnEng_ViewModel.WCFContact_Server.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/AllDictionaryEntries", ReplyAction="http://tempuri.org/IWCFContact_Server/AllDictionaryEntriesResponse")]
        LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO[] AllDictionaryEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/AllDictionaryEntries", ReplyAction="http://tempuri.org/IWCFContact_Server/AllDictionaryEntriesResponse")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO[]> AllDictionaryEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FindUserByName", ReplyAction="http://tempuri.org/IWCFContact_Server/FindUserByNameResponse")]
        LearnEng_ViewModel.WCFContact_Server.UserDTO FindUserByName(string nameOfUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FindUserByName", ReplyAction="http://tempuri.org/IWCFContact_Server/FindUserByNameResponse")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserDTO> FindUserByNameAsync(string nameOfUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/ConfigureAutoMapper", ReplyAction="http://tempuri.org/IWCFContact_Server/ConfigureAutoMapperResponse")]
        void ConfigureAutoMapper();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/ConfigureAutoMapper", ReplyAction="http://tempuri.org/IWCFContact_Server/ConfigureAutoMapperResponse")]
        System.Threading.Tasks.Task ConfigureAutoMapperAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchCountUserDictionary", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchCountUserDictionaryResponse")]
        int FetchCountUserDictionary(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchCountUserDictionary", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchCountUserDictionaryResponse")]
        System.Threading.Tasks.Task<int> FetchCountUserDictionaryAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchRangeUserDictionary", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchRangeUserDictionaryResponse")]
        LearnEng_ViewModel.WCFContact_Server.UserDictionaryEntryDTO[] FetchRangeUserDictionary(int startIndex, int count, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchRangeUserDictionary", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchRangeUserDictionaryResponse")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserDictionaryEntryDTO[]> FetchRangeUserDictionaryAsync(int startIndex, int count, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/CreateSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/CreateSaveEntityFromDTOResponse")]
        void CreateSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/CreateSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/CreateSaveEntityFromDTOResponse")]
        System.Threading.Tasks.Task CreateSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/DeleteSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/DeleteSaveEntityFromDTOResponse")]
        void DeleteSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/DeleteSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/DeleteSaveEntityFromDTOResponse")]
        System.Threading.Tasks.Task DeleteSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/UpdateSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/UpdateSaveEntityFromDTOResponse")]
        void UpdateSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/UpdateSaveEntityFromDTO", ReplyAction="http://tempuri.org/IWCFContact_Server/UpdateSaveEntityFromDTOResponse")]
        System.Threading.Tasks.Task UpdateSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FindIntegratedVacabularyEntryForWord", ReplyAction="http://tempuri.org/IWCFContact_Server/FindIntegratedVacabularyEntryForWordRespons" +
            "e")]
        LearnEng_ViewModel.WCFContact_Server.IntegratedVacabularyEntryDTO FindIntegratedVacabularyEntryForWord(string word, LearnEng_ViewModel.WCFContact_Server.Languages wordLanguage, LearnEng_ViewModel.WCFContact_Server.Languages translationLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FindIntegratedVacabularyEntryForWord", ReplyAction="http://tempuri.org/IWCFContact_Server/FindIntegratedVacabularyEntryForWordRespons" +
            "e")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.IntegratedVacabularyEntryDTO> FindIntegratedVacabularyEntryForWordAsync(string word, LearnEng_ViewModel.WCFContact_Server.Languages wordLanguage, LearnEng_ViewModel.WCFContact_Server.Languages translationLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchUserSettings", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchUserSettingsResponse")]
        LearnEng_ViewModel.WCFContact_Server.UserSettingsDTO FetchUserSettings(System.Guid userGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/FetchUserSettings", ReplyAction="http://tempuri.org/IWCFContact_Server/FetchUserSettingsResponse")]
        System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserSettingsDTO> FetchUserSettingsAsync(System.Guid userGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/Test", ReplyAction="http://tempuri.org/IWCFContact_Server/TestResponse")]
        void Test(LearnEng_ViewModel.WCFContact_Server.DTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFContact_Server/Test", ReplyAction="http://tempuri.org/IWCFContact_Server/TestResponse")]
        System.Threading.Tasks.Task TestAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFContact_ServerChannel : LearnEng_ViewModel.WCFContact_Server.IWCFContact_Server, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFContact_ServerClient : System.ServiceModel.ClientBase<LearnEng_ViewModel.WCFContact_Server.IWCFContact_Server>, LearnEng_ViewModel.WCFContact_Server.IWCFContact_Server {
        
        public WCFContact_ServerClient() {
        }
        
        public WCFContact_ServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFContact_ServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFContact_ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFContact_ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LearnEng_ViewModel.WCFContact_Server.UserGroupDTO[] AllUserGroupsOfUser(LearnEng_ViewModel.WCFContact_Server.UserDTO user) {
            return base.Channel.AllUserGroupsOfUser(user);
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserGroupDTO[]> AllUserGroupsOfUserAsync(LearnEng_ViewModel.WCFContact_Server.UserDTO user) {
            return base.Channel.AllUserGroupsOfUserAsync(user);
        }
        
        public LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO[] AllDictionaryEntries() {
            return base.Channel.AllDictionaryEntries();
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.DictionaryEntryDTO[]> AllDictionaryEntriesAsync() {
            return base.Channel.AllDictionaryEntriesAsync();
        }
        
        public LearnEng_ViewModel.WCFContact_Server.UserDTO FindUserByName(string nameOfUser) {
            return base.Channel.FindUserByName(nameOfUser);
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserDTO> FindUserByNameAsync(string nameOfUser) {
            return base.Channel.FindUserByNameAsync(nameOfUser);
        }
        
        public void ConfigureAutoMapper() {
            base.Channel.ConfigureAutoMapper();
        }
        
        public System.Threading.Tasks.Task ConfigureAutoMapperAsync() {
            return base.Channel.ConfigureAutoMapperAsync();
        }
        
        public int FetchCountUserDictionary(System.Guid userGuid) {
            return base.Channel.FetchCountUserDictionary(userGuid);
        }
        
        public System.Threading.Tasks.Task<int> FetchCountUserDictionaryAsync(System.Guid userGuid) {
            return base.Channel.FetchCountUserDictionaryAsync(userGuid);
        }
        
        public LearnEng_ViewModel.WCFContact_Server.UserDictionaryEntryDTO[] FetchRangeUserDictionary(int startIndex, int count, System.Guid userGuid) {
            return base.Channel.FetchRangeUserDictionary(startIndex, count, userGuid);
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserDictionaryEntryDTO[]> FetchRangeUserDictionaryAsync(int startIndex, int count, System.Guid userGuid) {
            return base.Channel.FetchRangeUserDictionaryAsync(startIndex, count, userGuid);
        }
        
        public void CreateSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            base.Channel.CreateSaveEntityFromDTO(dto);
        }
        
        public System.Threading.Tasks.Task CreateSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            return base.Channel.CreateSaveEntityFromDTOAsync(dto);
        }
        
        public void DeleteSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            base.Channel.DeleteSaveEntityFromDTO(dto);
        }
        
        public System.Threading.Tasks.Task DeleteSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            return base.Channel.DeleteSaveEntityFromDTOAsync(dto);
        }
        
        public void UpdateSaveEntityFromDTO(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            base.Channel.UpdateSaveEntityFromDTO(dto);
        }
        
        public System.Threading.Tasks.Task UpdateSaveEntityFromDTOAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            return base.Channel.UpdateSaveEntityFromDTOAsync(dto);
        }
        
        public LearnEng_ViewModel.WCFContact_Server.IntegratedVacabularyEntryDTO FindIntegratedVacabularyEntryForWord(string word, LearnEng_ViewModel.WCFContact_Server.Languages wordLanguage, LearnEng_ViewModel.WCFContact_Server.Languages translationLanguage) {
            return base.Channel.FindIntegratedVacabularyEntryForWord(word, wordLanguage, translationLanguage);
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.IntegratedVacabularyEntryDTO> FindIntegratedVacabularyEntryForWordAsync(string word, LearnEng_ViewModel.WCFContact_Server.Languages wordLanguage, LearnEng_ViewModel.WCFContact_Server.Languages translationLanguage) {
            return base.Channel.FindIntegratedVacabularyEntryForWordAsync(word, wordLanguage, translationLanguage);
        }
        
        public LearnEng_ViewModel.WCFContact_Server.UserSettingsDTO FetchUserSettings(System.Guid userGUID) {
            return base.Channel.FetchUserSettings(userGUID);
        }
        
        public System.Threading.Tasks.Task<LearnEng_ViewModel.WCFContact_Server.UserSettingsDTO> FetchUserSettingsAsync(System.Guid userGUID) {
            return base.Channel.FetchUserSettingsAsync(userGUID);
        }
        
        public void Test(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            base.Channel.Test(dto);
        }
        
        public System.Threading.Tasks.Task TestAsync(LearnEng_ViewModel.WCFContact_Server.DTO dto) {
            return base.Channel.TestAsync(dto);
        }
    }
}
